# Generated by Django 5.2.2 on 2025-06-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userquizattempt_all_concepts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='all_concepts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
